[project]
name = "kreativeu-catalogue-pipeline"
version = "0.0.2"
description = ""
authors = [ { name = "Lars Lewerentz", email = "lars.lewerentz@uni-greifswald.de" } ]
requires-python = ">=3.14,<3.15"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "bleach==6.4.0",
  "defusedxml==0.7.1",
  "gitpython==3.1.58",
  "markdownify==1.2.3",
  "playwright==1.61.0",
  "pydantic[email]==2.13.4",
  "python-dotenv==1.2.2",
  "urllib3==2.7.0",
  "xmltodict==1.0.4",
]
